[build]
command = "yarn build"
publish = "public/"
[dev]
command = "yarn develop"

[context.production]
command = "yarn build"
publish = "public/"

[[plugins]]
package = "@netlify/plugin-gatsby"

[[plugins]]
package = "netlify-plugin-cache"
[plugins.inputs]
paths = [".cache", "public"]
