interface Project = {
  title: string;
  slug: string;
  client?: string;
  description: {
    id?: string;
    description: string;
  };
  projectCompletionDate?: Date;
  featureImage: contentfulAsset
  projectImages: [contentfulAsset]
}

interface CaseStudy = {
  title: string;
  slug: string;
  heroImage: contentfulAsset;
  tableOfContents: contentfulLongText;
  post: contentfulLongText;
}

interface contentfulLongText = {
  id?: number;
  internal: {
    type?: string;
    mediaType: string;
    content: string;
    contentDigest?: string;
    owner?: string;
  }
  // this is generated by gatsby-transformer-remark
  // it's not a contentful thing
  childMarkdownRemark: {
    html: string;
  }
}

interface contentfulAsset = {
  id?: string;
  resolutions: {
    src: string;
    base64?: string;
    tracedSVG?: string;
    aspectRatio?: number;
    width?: number;
    height?: number;
    srcSet?: string;
    srcWebp?: string;
    srcSetWebp?: string;    
  };
}
