declare module '*.scss' {
  const content: {[className: string]: string};
  export = content;
}

interface PortfolioItem {
  title: string;
  slug: string;
  featureImage: contentfulAsset;
  featureOnHomepage: boolean;
}

interface Project extends PortfolioItem {
  client?: string;
  description: {
    id?: string;
    description: string;
  };
  projectCompletionDate?: Date;
  projectImages: [contentfulAsset]
}

interface CaseStudy extends PortfolioItem {
  tableOfContents: contentfulLongText;
  post: contentfulLongText;
}

interface AboutPageData {
  title: string;
  post: contentfulLongText;
  featureImage: contentfulAsset;
}

interface contentfulLongText {
  id?: number;
  internal: {
    type?: string;
    mediaType: string;
    content: string;
    contentDigest?: string;
    owner?: string;
  }
  // this is generated by gatsby-transformer-remark
  // it's not a contentful thing
  childMarkdownRemark: {
    html: string;
  }
}

interface contentfulAsset {
  id?: string;
  resolutions: {
    src: string;
    base64?: string;
    tracedSVG?: string;
    aspectRatio?: number;
    width?: number;
    height?: number;
    srcSet?: string;
    srcWebp?: string;
    srcSetWebp?: string;    
  };
}
